name: histoslider
channels:
  - defaults
dependencies:
  - git
  - pip
  - python=3.7
  - setuptools
  - tk
  - wheel
  - pip:
    - PyQt5
    - numpy
    - psutil
    - scikit-image
    - opencv-python-headless
    - qimage2ndarray
    - git+https://github.com/pyqtgraph/pyqtgraph
    - git+https://github.com/BodenmillerGroup/imctools.git
    - git+https://github.com/BodenmillerGroup/HistoSlider.git
