name: histoslider
channels:
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - openssl
  - pip
  - python=3.7
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
    - PyQt5
    - numpy
    - pyqtgraph
    - psutil
    - pytest
    - pyqt-distutils
    - PyInstaller
    - flake8
    - scikit-image
    - opencv-python
    - git+https://github.com/BodenmillerGroup/imctools.git
    - git+https://github.com/BodenmillerGroup/HistoSlider.git
